export const CLIENT_LIBRARIES = [
  {
    language: 'JavaScript',
    officialSupport: true,
    releaseState: undefined,
    docsUrl: 'https://supabase.com/docs/reference/javascript/installing',
    gitUrl: 'https://github.com/supabase/supabase-js',
  },
  {
    language: 'Flutter',
    officialSupport: true,
    releaseState: undefined,
    docsUrl: 'https://supabase.com/docs/reference/dart/installing',
    gitUrl: 'https://github.com/supabase/supabase-flutter',
  },
  {
    language: 'Python',
    officialSupport: false,
    releaseState: 'Alpha',
    docsUrl: 'https://supabase.com/docs/reference/python/initializing',
    gitUrl: 'https://github.com/supabase/supabase-py',
  },
  {
    language: 'C#',
    officialSupport: false,
    releaseState: undefined,
    docsUrl: 'https://supabase.com/docs/reference/csharp/installing',
    gitUrl: 'https://github.com/supabase-community/supabase-csharp',
    altIconName: 'c-sharp',
  },
  {
    language: 'Swift',
    officialSupport: false,
    releaseState: undefined,
    docsUrl: 'https://supabase.com/docs/reference/swift/initializing',
    gitUrl: 'https://github.com/supabase-community/supabase-swift',
  },
  {
    language: 'Kotlin',
    officialSupport: false,
    releaseState: undefined,
    docsUrl: 'https://supabase.com/docs/reference/kotlin/installing',
    gitUrl: 'https://github.com/supabase-community/supabase-kt',
  },
]

export const EXAMPLE_PROJECTS = [
  {
    framework: 'Svelte',
    title: 'Svelte看板',
    description: '使用Supadase作为存储系统的Trello克隆',
    url: 'https://github.com/joshnuss/supabase-kanban',
  },
  {
    framework: 'NextJS',
    title: 'Next.js实时聊天应用',
    description: 'Next.js Slack克隆应用Suabase实时订阅',
    url: 'https://github.com/supabase/supabase/tree/master/examples/slack-clone/nextjs-slack-clone',
  },
  {
    framework: 'NextJS',
    title: 'Next.js订阅与身份验证',
    description: '用于高性能SaaS应用程序的一体化入门套件',
    url: 'https://github.com/vercel/nextjs-subscription-payments',
  },
  {
    framework: 'Expo',
    title: 'Expo上手',
    description: '身份验证流程模板底部选项卡(Typescript)',
    url: 'https://github.com/codingki/react-native-expo-template/tree/master/template-typescript-bottom-tabs-supabase-auth-flow',
  },
  {
    framework: 'NestJS',
    title: 'NestJS示例',
    description: 'NestJS Supabase验证示例',
    url: 'https://github.com/hiro1107/nestjs-supabase-auth',
  },
  {
    framework: 'React',
    title: 'React实时聊天应用',
    description: '示例应用：使用Supabase实时API的实时聊天',
    url: 'https://github.com/shwosner/realtime-chat-supabase-react',
  },
  {
    framework: 'JavaScript',
    title: 'Vanilla-js身份验证',
    description: '示例应用：使用Supabase实时API的实时聊天',
    url: 'https://github.com/supabase/examples/tree/main/supabase-js-v1/auth/javascript-auth',
  },
  {
    framework: 'React',
    title: 'React Native待办事项',
    description: 'React Native与Expo待办事项示例',
    url: 'https://github.com/supabase/examples/tree/main/supabase-js-v1/todo-list/expo-todo-list',
  },
  {
    framework: 'NextJS',
    title: 'Next.js待办事项',
    description: 'NextJS待办事项示例',
    url: 'https://github.com/supabase/supabase/tree/master/examples/todo-list/nextjs-todo-list',
  },
  {
    framework: 'React',
    title: 'React待办事项',
    description: 'React待办事项示例',
    url: 'https://github.com/supabase/examples/tree/main/supabase-js-v1/todo-list/react-todo-list',
  },
  {
    framework: 'Svelte',
    title: 'Svelte待办事项',
    description: 'Sveltejs TailwindCSS与Snowpack待办事项',
    url: 'https://github.com/supabase/supabase/tree/master/examples/todo-list/sveltejs-todo-list',
  },
  {
    framework: 'VueJS',
    title: 'Vue.js待办事项',
    description: 'Vue.js使用TypeScript待办事项',
    url: 'https://github.com/supabase/examples/tree/main/supabase-js-v1/todo-list/vue3-ts-todo-list',
  },
]
